/** Owned UI copy for source-reading LLM narratives; model-generated prose remains literal source-adjacent content. */
export function getFunctionNarrativeCatalogSource(): string {
  const en = {
    "model-task-queued": "Queued · position {position} · {waiting} waiting",
    "model-task-preparing": "Preparing the model…", "model-task-running": "The model is reading the source…",
    "model-task-cancelling": "Stopping the model and releasing resources…",
    "narrative-queue-full": "The model queue is full. Wait for a task to finish or cancel a waiting task in Model Tasks, then retry.",
    "narrative-heading": "Plain-language explanation", "narrative-action": "Analyze all scenarios", "narrative-complete": "Explanation generated",
    "narrative-guide-description": "Source paths and model explanations · source code is never executed",
    "narrative-continue": "Continue scenario analysis", "narrative-progress": "Analyzed {count} scenarios; processing remaining source paths…",
    "narrative-progress-total": "Analyzed {count} of {total} scenarios…", "narrative-page-loading": "Loading saved scenarios…",
    "narrative-partial-status": "Analyzed {count} scenarios. Continue to analyze remaining paths.",
    "narrative-page-label": "Results {page} of {pages} · scenarios {start}–{end}", "narrative-previous": "Previous scenarios", "narrative-next": "Next scenarios",
    "narrative-source-incomplete": "All discovered scenarios were analyzed, but omitted or unsupported source may contain additional paths.",
    "narrative-evidence": "Source evidence",
    "narrative-completion-status": "Generated {count} behavior scenarios.",
    "narrative-help": "Analyze every source path in sequential batches. Local mode downloads its model on first use and releases model memory when finished. You can cancel and resume; completed scenarios are retained.",
    "narrative-idle": "Read conditions, work and results as connected sentences.", "narrative-pending": "Preparing the model and reading the function…", "narrative-cancel": "Cancel",
    "narrative-ready": "Model/source reading · execution unverified", "narrative-unavailable": "Install llama.cpp and set its llama-completion path in Project Analyzer settings, or connect a VS Code Chat model. The default local model downloads automatically.",
    "narrative-download-failed": "Model preparation failed. Check network/proxy settings and disk space, then retry. An interrupted download resumes automatically.",
    "narrative-cancelled": "Generation cancelled. You can try again.", "narrative-denied": "Model access was declined. Allow access through VS Code to retry.",
    "narrative-timeout": "This scenario batch timed out. Completed scenarios are retained; continue to retry the remaining paths.", "narrative-invalid-response": "The model response could not be validated. Try again.",
    "narrative-language-mismatch": "The model did not use the requested language. Generate again to retry.",
    "narrative-context-too-large": "The function exceeds the model's input window or the 32-parameter example limit. Analyze a smaller function, or choose a model with a larger input window for long source code.",
    "narrative-failed": "The model request failed. Open Model Tasks to inspect the failed phase, then retry.", "narrative-stale": "The function context expired. Reload this function, then generate again.", "narrative-refresh": "Reload function",
    "narrative-when": "Conditions", "narrative-outcome": "Expected outcome", "narrative-assumptions": "Assumptions", "narrative-limitations": "Missing information",
    "narrative-reason": "Reason", "narrative-effect": "Value and flow changes",
    "narrative-syntax": "Syntax meaning", "narrative-path-reason": "Why this path",
    "narrative-state-change": "State and effects", "narrative-alternative": "What changes the path",
    "narrative-example-basis": "Input example · execution unverified", "narrative-no-inputs": "No parameters",
    "narrative-example-result": "Example result", "narrative-select": "Select scenario", "narrative-show-graph": "Show on graph",
    "narrative-apply-example": "Apply example values", "narrative-example-loaded": "Example values loaded. You can edit them here.",
    "narrative-node-heading": "Selected node explanation", "narrative-node-label": "Node in this scenario",
    "narrative-graph-notes": "Graph notes", "narrative-graph-notes-help": "Show or hide this scenario's saved explanations.",
    "narrative-graph-notes-empty": "Analyze scenarios in the Guide to prepare graph notes.",
    "narrative-graph-notes-scenario": "Saved explanations for scenario {scenario}",
    "narrative-graph-note-expand": "Read explanation · {count} visits",
    "narrative-graph-note-open": "Open scenario {scenario} note · L{line}",
    "narrative-graph-note-zoom": "Saved note · L{line} · zoom in to read",
    "narrative-node-outside": "Selected graph node · outside this scenario", "narrative-node-skipped": "This scenario does not reach the selected node.",
    "narrative-node-pending": "This node's explanation is not saved yet. Continue scenario analysis to prepare it.",
    "narrative-node-unavailable": "The supplied source does not include a supported operation for this node.",
    "narrative-node-other-example": "Explanation from scenario {scenario} · {inputs}", "narrative-node-visit": "Visit {visit}",
    "narrative-node-values": "Example value changes", "narrative-before": "Before", "narrative-after": "After",
    "narrative-node-source": "Open source · L{line}", "narrative-editable-examples": "Edit example values here. This language's runtime evaluation is unavailable.",
    "narrative-model-examples-action": "Generate model examples", "narrative-model-examples-title": "Open the explanation and analyze scenarios with the connected model.",
    "narrative-limited": "Only excerpts were supplied. Omitted code may change the behavior.", "narrative-source": "Source · {scenario}.{step} · L{start}–{end}",
    "narrative-source-help": "Open a cited line to read its LLM annotation in VS Code. Source edits clear the annotations.",
    "narrative-cached": "Reused this snapshot's result", "narrative-language": "Generated in {language}", "narrative-language-ko": "Korean", "narrative-language-en": "English"
  };
  const ko: Record<keyof typeof en, string> = {
    "model-task-queued": "모델 작업 대기 · 순서 {position} · 대기 {waiting}개",
    "model-task-preparing": "모델을 준비하고 있습니다…", "model-task-running": "모델이 소스를 읽고 있습니다…",
    "model-task-cancelling": "모델을 중단하고 자원을 정리하고 있습니다…",
    "narrative-queue-full": "모델 작업 대기열이 가득 찼습니다. 완료를 기다리거나 모델 작업에서 대기 작업을 취소한 뒤 다시 시도하세요.",
    "narrative-heading": "문장형 설명", "narrative-action": "전체 시나리오 분석", "narrative-complete": "설명 생성됨",
    "narrative-guide-description": "소스 경로와 모델 해설 · 소스 코드를 실행하지 않습니다",
    "narrative-continue": "이어서 시나리오 분석", "narrative-progress": "시나리오 {count}개 분석 · 남은 소스 경로를 처리하고 있습니다…",
    "narrative-progress-total": "전체 {total}개 중 {count}개 분석 중…", "narrative-page-loading": "저장된 시나리오를 불러오는 중…",
    "narrative-partial-status": "시나리오 {count}개를 분석했습니다. 이어서 남은 경로를 분석할 수 있습니다.",
    "narrative-page-label": "결과 {page}/{pages} · 시나리오 {start}–{end}", "narrative-previous": "이전 시나리오", "narrative-next": "다음 시나리오",
    "narrative-source-incomplete": "발견한 시나리오는 모두 분석했지만 생략되거나 지원하지 않는 소스에 추가 경로가 있을 수 있습니다.",
    "narrative-evidence": "소스 근거",
    "narrative-completion-status": "동작 시나리오 {count}개를 만들었습니다.",
    "narrative-help": "함수의 모든 소스 경로를 순차 분석합니다. 로컬 모델은 첫 사용 때 자동 다운로드하고 생성 후 메모리를 해제합니다. 취소 후 이어서 진행할 수 있고 완료된 시나리오는 보존합니다.",
    "narrative-idle": "조건부터 동작과 결과까지 이어지는 문장으로 읽습니다.", "narrative-pending": "모델을 준비하고 함수를 읽는 중…", "narrative-cancel": "취소",
    "narrative-ready": "모델·소스 해설 · 실제 실행 미검증", "narrative-unavailable": "llama.cpp를 설치하고 Project Analyzer 설정에 llama-completion 경로를 지정하거나 VS Code Chat 모델을 연결하세요. 기본 로컬 모델은 자동 다운로드합니다.",
    "narrative-download-failed": "모델 준비에 실패했습니다. 네트워크·프록시 설정과 저장 공간을 확인한 뒤 다시 분석하세요. 중단된 다운로드는 자동으로 이어받습니다.",
    "narrative-cancelled": "생성을 취소했습니다. 다시 시도할 수 있습니다.", "narrative-denied": "모델 접근이 거부되었습니다. VS Code에서 접근을 허용한 뒤 다시 시도하세요.",
    "narrative-timeout": "현재 시나리오 묶음의 응답 시간이 초과됐습니다. 완료된 결과는 보존합니다. 이어서 남은 경로를 다시 분석하세요.", "narrative-invalid-response": "모델 응답의 형식이나 소스 위치를 확인하지 못했습니다. 다시 시도하세요.",
    "narrative-language-mismatch": "모델이 요청한 언어로 설명하지 않았습니다. 설명 생성을 다시 눌러 시도하세요.",
    "narrative-context-too-large": "함수가 모델 입력 한도 또는 예시값의 매개변수 32개 한도를 넘었습니다. 더 작은 함수를 분석하거나, 소스가 긴 경우 입력 한도가 더 큰 모델을 선택하세요.",
    "narrative-failed": "모델 요청에 실패했습니다. 모델 작업에서 실패한 단계를 확인한 뒤 다시 시도하세요.", "narrative-stale": "함수 컨텍스트가 만료되었습니다. 함수를 다시 불러온 뒤 생성하세요.", "narrative-refresh": "함수 다시 불러오기",
    "narrative-when": "조건", "narrative-outcome": "예상 결과", "narrative-assumptions": "가정", "narrative-limitations": "미확인 부분",
    "narrative-reason": "판단 근거", "narrative-effect": "값과 흐름의 변화",
    "narrative-syntax": "구문 의미", "narrative-path-reason": "이 경로를 선택하는 이유",
    "narrative-state-change": "상태와 부수 효과", "narrative-alternative": "다른 경로로 바뀌는 조건",
    "narrative-example-basis": "입력 예시 · 실제 실행 미검증", "narrative-no-inputs": "매개변수 없음",
    "narrative-example-result": "예상 결과값", "narrative-select": "시나리오 선택", "narrative-show-graph": "그래프에서 보기",
    "narrative-apply-example": "예시값 적용", "narrative-example-loaded": "예시값을 불러왔습니다. 여기에서 수정할 수 있습니다.",
    "narrative-node-heading": "선택한 노드 해설", "narrative-node-label": "이 시나리오의 노드",
    "narrative-graph-notes": "그래프 노트", "narrative-graph-notes-help": "이 시나리오의 저장된 해설을 표시하거나 숨깁니다.",
    "narrative-graph-notes-empty": "Guide에서 시나리오를 분석하면 그래프 노트를 볼 수 있습니다.",
    "narrative-graph-notes-scenario": "시나리오 {scenario}의 저장된 해설",
    "narrative-graph-note-expand": "해설 펼치기 · 방문 {count}회",
    "narrative-graph-note-open": "시나리오 {scenario} 노트 열기 · L{line}",
    "narrative-graph-note-zoom": "저장된 노트 · L{line} · 확대해서 읽기",
    "narrative-node-outside": "선택한 그래프 노드 · 이 시나리오 밖", "narrative-node-skipped": "이 시나리오는 선택한 노드를 지나지 않습니다.",
    "narrative-node-pending": "이 노드의 해설은 아직 저장되지 않았습니다. 시나리오 분석을 이어서 준비하세요.",
    "narrative-node-unavailable": "전달된 소스에서 이 노드의 동작을 확인하지 못했습니다.",
    "narrative-node-other-example": "시나리오 {scenario}의 해설 · {inputs}", "narrative-node-visit": "{visit}번째 방문",
    "narrative-node-values": "예시값의 변화", "narrative-before": "이전", "narrative-after": "이후",
    "narrative-node-source": "소스 열기 · L{line}", "narrative-editable-examples": "예시값을 여기에서 수정할 수 있습니다. 이 언어의 런타임 계산은 지원하지 않습니다.",
    "narrative-model-examples-action": "모델 예시 생성", "narrative-model-examples-title": "설명을 열고 연결된 모델로 시나리오를 분석합니다.",
    "narrative-limited": "코드 일부만 전달했습니다. 생략한 코드에 따라 동작이 달라질 수 있습니다.", "narrative-source": "소스 · {scenario}.{step} · L{start}–{end}",
    "narrative-source-help": "인용한 줄을 열면 VS Code에서 LLM 해설을 확인할 수 있습니다. 소스를 수정하면 표시가 지워집니다.",
    "narrative-cached": "이 스냅샷의 결과 재사용", "narrative-language": "생성 언어: {language}", "narrative-language-ko": "한국어", "narrative-language-en": "영어"
  };
  return `Object.assign(projectAnalyzerUiCopy.en, ${JSON.stringify(en)}); Object.assign(projectAnalyzerUiCopy.ko, ${JSON.stringify(ko)});`;
}
