/** Korean/English source-backed behavior and representative scenario Summary copy. */
export function getFunctionSummaryCatalogSource(): string {
  return /* js */ `
    Object.assign(projectAnalyzerUiCopy.en, {
      "scenario-model-work":"Calls and writes in order", "scenario-model-checked":"Checked", "scenario-model-assumed":"Assumed",
      "scenario-model-gap-missing-block":"A source block is unavailable", "scenario-model-gap-disconnected-route":"The remaining route could not be verified", "scenario-model-gap-deferred-boundary":"A defined or deferred body is outside this execution scope", "scenario-model-gap-path-limit":"The path reached an analysis limit", "scenario-model-gap-unknown-terminal":"The terminal is unresolved", "scenario-model-gap-unresolved-call":"The call target or result is unverified", "scenario-model-gap-unsupported-operation":"This operation is unsupported", "scenario-model-gap-unknown-value":"A calculated value remains unknown", "scenario-model-gap-value-limit":"A value could not be safely shown within preview limits", "scenario-model-gap-analysis-gap":"This route has an analysis gap",
      "scenario-empty-symbolic":"No tracked lexical bindings. Source paths remain available below.",
      "scenario-outcome-default":"default", "scenario-outcome-iterate":"loop body", "scenario-outcome-exit":"loop exit", "scenario-outcome-exception":"exception branch", "scenario-outcome-next":"normal continuation", "scenario-outcome-repeat":"loop back", "scenario-outcome-loop-back":"loop back", "scenario-path-source":"Straight source path",
      "summary-heading":"Function summary", "summary-purpose":"Role", "summary-documentation":"Source documentation", "summary-structure":"Source structure",
      "summary-purpose-structure":"Source declares {inputs} inputs, {calls} calls, {writes} writes, {returns} return forms and {throws} throw forms.",
      "summary-ready":"Source structure available", "summary-partial":"Partial source summary · review the gaps", "summary-unavailable":"No supported current-scope behavior is available. Open the source to continue.",
      "summary-inputs":"Inputs", "summary-outcomes":"Outcomes", "summary-stages":"Main source stages", "summary-stages-note":"Conditions and alternatives describe source structure. They are not one execution order.",
      "summary-no-inputs":"No declared inputs", "summary-no-outcomes":"No supported source outcome found", "summary-no-stages":"No supported stage found", "summary-impacts":"Calls and writes", "summary-gaps":"Summary gaps", "summary-context":"Owner and callers",
      "summary-default":"Declared default: {value}", "summary-optional":"Optional argument", "summary-rest":"Variable arguments", "summary-none":"None in the supported source scope",
      "summary-item-parameter":"Input", "summary-item-condition":"Condition", "summary-item-loop":"Loop", "summary-item-switch":"Alternatives", "summary-item-try":"Exception boundary",
      "summary-item-call":"Source call", "summary-item-external-call":"External call", "summary-item-unresolved-call":"Unresolved call", "summary-item-write":"Source write", "summary-item-effect":"Effect boundary", "summary-item-return":"Return expression", "summary-item-throw":"Throw expression", "summary-item-exit":"Scope exit",
      "summary-scope-source":"Source stage", "summary-scope-conditional":"Conditional", "summary-scope-repeated":"Repeated · count unverified", "summary-scope-finally":"Finally",
      "summary-gap-analysis":"Analysis gap", "summary-gap-boundary":"Defined or deferred bodies are excluded from the current execution scope.", "summary-gap-external":"An external call is visible; its result and external effect are unverified.", "summary-gap-unresolved":"A call target or result is unresolved.", "summary-gap-limit":"Current-scope traversal reached an analysis limit.", "summary-gap-unknown":"This source stage could not be interpreted.",
      "summary-omitted":"{count} additional items not displayed here", "summary-analysis-limited":"Analysis is bounded; omitted display items are counted separately.",
      "summary-representatives":"Representative scenarios", "summary-representatives-note":"Inputs and source choices → calls and writes → terminal and gaps. Selecting a row previews the shared path.",
      "summary-show-more":"Show up to 5 scenarios", "summary-show-less":"Show 3 scenarios", "summary-other-scenarios":"{count} other scenarios remain in the detailed table", "summary-pending":"Waiting for a completed source path.",
      "summary-concrete":"Calculated values", "summary-symbolic":"Symbolic path", "summary-path-partial":"Partial", "summary-concrete-note":"Values were calculated by the bounded static evaluator; external execution was not observed.", "summary-symbolic-note":"Source choices are assumed; input satisfaction and actual execution are unverified.",
      "summary-input-conditions":"Inputs and conditions", "summary-calls-writes":"Calls and writes", "summary-terminal-gaps":"Terminal and gaps", "summary-no-conditions":"No source decision on this path", "summary-no-effects":"No supported call or write on this path", "summary-terminal-source":"Source terminal: {source}", "summary-terminal-unknown":"Terminal remains unknown", "summary-terminal-value":"Calculated return: {value}", "summary-path-assumptions":"Assumptions: {value}", "summary-path-gaps":"Path gaps: {count}", "summary-title-return":"Return path {ordinal}", "summary-title-throw":"Throw path {ordinal}", "summary-title-exit":"Exit path {ordinal}", "summary-title-unknown":"Partial path {ordinal}", "summary-symbolic-disabled":"Value calculation and input application are unavailable for this language. Use source path preview and playback."
    });
    Object.assign(projectAnalyzerUiCopy.ko, {
      "scenario-model-work":"순서대로 보는 호출과 쓰기", "scenario-model-checked":"검증됨", "scenario-model-assumed":"가정됨",
      "scenario-model-gap-missing-block":"소스 블록을 확인할 수 없음", "scenario-model-gap-disconnected-route":"이후 경로를 검증하지 못함", "scenario-model-gap-deferred-boundary":"정의되거나 나중에 실행되는 본문은 현재 실행 범위 밖임", "scenario-model-gap-path-limit":"경로 분석 상한에 도달함", "scenario-model-gap-unknown-terminal":"종료를 확인하지 못함", "scenario-model-gap-unresolved-call":"호출 대상 또는 결과가 검증되지 않음", "scenario-model-gap-unsupported-operation":"지원하지 않는 연산", "scenario-model-gap-unknown-value":"계산값을 확인하지 못함", "scenario-model-gap-value-limit":"값을 미리 보기 범위에서 안전하게 표시하지 못함", "scenario-model-gap-analysis-gap":"이 경로에 분석 미확인 구간이 있음",
      "scenario-empty-symbolic":"추적한 어휘 바인딩이 없습니다. 아래에서 소스 경로를 확인할 수 있습니다.",
      "scenario-outcome-default":"기본 경로", "scenario-outcome-iterate":"반복 본문", "scenario-outcome-exit":"반복 종료", "scenario-outcome-exception":"예외 분기", "scenario-outcome-next":"정상 진행", "scenario-outcome-repeat":"다음 반복", "scenario-outcome-loop-back":"다음 반복", "scenario-path-source":"분기 없는 소스 경로",
      "summary-heading":"함수 요약", "summary-purpose":"역할", "summary-documentation":"소스 문서", "summary-structure":"소스 구조",
      "summary-purpose-structure":"소스에 입력 {inputs}개, 호출 {calls}개, 쓰기 {writes}개, 반환 형태 {returns}개, 예외 형태 {throws}개가 있습니다.",
      "summary-ready":"소스 구조 확인됨", "summary-partial":"일부만 확인한 소스 요약 · 미확인 부분을 확인하세요", "summary-unavailable":"현재 실행 범위에서 지원하는 행동을 확인하지 못했습니다. 소스를 열어 확인하세요.",
      "summary-inputs":"입력", "summary-outcomes":"결과", "summary-stages":"주요 소스 단계", "summary-stages-note":"조건과 대안은 소스 구조를 설명합니다. 하나의 실행 순서를 뜻하지 않습니다.",
      "summary-no-inputs":"선언된 입력 없음", "summary-no-outcomes":"지원하는 소스 결과를 확인하지 못함", "summary-no-stages":"지원하는 단계를 확인하지 못함", "summary-impacts":"호출과 쓰기", "summary-gaps":"요약의 미확인 부분", "summary-context":"소유 구조와 호출자",
      "summary-default":"선언된 기본값: {value}", "summary-optional":"생략 가능한 인자", "summary-rest":"가변 인자", "summary-none":"지원하는 소스 범위에 없음",
      "summary-item-parameter":"입력", "summary-item-condition":"조건", "summary-item-loop":"반복", "summary-item-switch":"조건별 대안", "summary-item-try":"예외 경계",
      "summary-item-call":"소스 호출", "summary-item-external-call":"외부 호출", "summary-item-unresolved-call":"미확인 호출", "summary-item-write":"소스 쓰기", "summary-item-effect":"효과 경계", "summary-item-return":"반환식", "summary-item-throw":"예외식", "summary-item-exit":"범위 종료",
      "summary-scope-source":"소스 단계", "summary-scope-conditional":"조건부", "summary-scope-repeated":"반복 · 횟수 미확인", "summary-scope-finally":"finally 구간",
      "summary-gap-analysis":"분석 미확인 부분", "summary-gap-boundary":"정의되거나 나중에 실행되는 내부 본문은 현재 실행 범위에서 제외합니다.", "summary-gap-external":"외부 호출은 확인했지만 결과와 외부 영향은 검증하지 않았습니다.", "summary-gap-unresolved":"호출 대상 또는 결과를 확인하지 못했습니다.", "summary-gap-limit":"현재 실행 범위 탐색이 분석 상한에 도달했습니다.", "summary-gap-unknown":"이 소스 단계를 해석하지 못했습니다.",
      "summary-omitted":"이곳에 표시하지 않은 항목 {count}개", "summary-analysis-limited":"분석 범위에 상한이 있습니다. 화면에 생략한 항목 수와는 별개입니다.",
      "summary-representatives":"대표 시나리오", "summary-representatives-note":"입력·소스 조건 → 호출·쓰기 → 종료·미확인 부분. 행을 선택하면 공유 경로를 미리 봅니다.",
      "summary-show-more":"최대 5개 시나리오 보기", "summary-show-less":"3개 시나리오 보기", "summary-other-scenarios":"다른 시나리오 {count}개는 상세 표에서 확인할 수 있습니다", "summary-pending":"완료된 소스 경로를 기다리는 중입니다.",
      "summary-concrete":"값 계산됨", "summary-symbolic":"기호 경로", "summary-path-partial":"일부만 확인", "summary-concrete-note":"제한된 정적 계산기로 값을 계산했습니다. 외부 실행을 관찰한 결과는 아닙니다.", "summary-symbolic-note":"소스 조건을 가정한 경로입니다. 입력이 조건을 충족하는지와 실제 실행 여부는 검증하지 않았습니다.",
      "summary-input-conditions":"입력과 조건", "summary-calls-writes":"호출과 쓰기", "summary-terminal-gaps":"종료와 미확인 부분", "summary-no-conditions":"이 경로에 소스 분기 없음", "summary-no-effects":"이 경로에 지원하는 호출·쓰기 없음", "summary-terminal-source":"소스 종료: {source}", "summary-terminal-unknown":"종료 미확인", "summary-terminal-value":"계산된 반환: {value}", "summary-path-assumptions":"가정: {value}", "summary-path-gaps":"미확인 구간: {count}개", "summary-title-return":"반환 경로 {ordinal}", "summary-title-throw":"예외 경로 {ordinal}", "summary-title-exit":"종료 경로 {ordinal}", "summary-title-unknown":"일부만 확인한 경로 {ordinal}", "summary-symbolic-disabled":"이 언어는 값 계산과 입력 적용을 지원하지 않습니다. 소스 경로 미리 보기와 재생을 사용하세요."
    });
  `;
}
