/** Bilingual reading prompts, step explanations and framework disclosure chrome. */
export function getFunctionUnderstandingCatalogSource(): string {
  return /* js */ `
    Object.assign(projectAnalyzerUiCopy.en, {
      "understanding-title":"At a glance", "understanding-hint":"Start with inputs, follow the decisions, then inspect what leaves the function.",
      "understanding-inputs":"1 · What comes in?", "understanding-decisions":"2 · What changes the path?", "understanding-outcomes":"3 · What comes out?",
      "understanding-no-inputs":"No declared parameters", "understanding-more":" + {count} more", "understanding-input-action":"Read inputs",
      "understanding-decision-count":"{count} decision points", "understanding-no-decisions":"No branch or loop in the displayed code", "understanding-decision-action":"Read the first decision",
      "understanding-outcome-returns":"{count} return sites", "understanding-outcome-errors":"{count} error sites", "understanding-outcome-effects":"{count} identified effect sites",
      "understanding-no-outcomes":"No explicit return, throw or effect identified in the displayed code", "understanding-outcome-action":"Read the first outcome",
      "understanding-empty":"There are no source steps to explain yet.", "understanding-documentation":"From the function's documentation",
      "understanding-framework":"Understand {framework} behavior", "understanding-framework-note":"Framework contracts linked to this source. Actual scheduling, requests and SQL were not observed.",
      "understanding-framework-more":"{count} additional facts omitted by the analysis limit.", "understanding-framework-limited":"Only the bounded source region was analyzed.",
      "understanding-graph":"Find on graph", "understanding-source":"Open source evidence", "understanding-evidence-missing":"Source evidence is unavailable in this snapshot.",
      "understanding-no-framework":"No source-backed React or Django behavior was identified for this function.",
      "understanding-role-component":"Component", "understanding-role-hooks":"React Hooks", "understanding-role-view":"Request handler", "understanding-role-signal":"Signal receiver", "understanding-role-middleware":"Middleware", "understanding-role-usage":"Framework API usage",
      "understanding-phase-render":"While rendering", "understanding-phase-commit":"After DOM commit", "understanding-phase-event":"On interaction", "understanding-phase-request":"During request handling", "understanding-phase-query":"Database work", "understanding-phase-response":"Response construction", "understanding-phase-registration":"Callback registration",
      "understanding-step-heading":"What this step means",
      "understanding-step-entry":"Start here: check the values passed into the function, then follow the first statement.",
      "understanding-step-condition":"This is a fork in the path. Compare what happens when the condition is true and when it is false below.",
      "understanding-step-loop":"This body can run repeatedly. Find what continues the loop and what takes the exit path.",
      "understanding-step-switch":"The value chooses a matching case. Check the default path for values that do not match.",
      "understanding-step-return":"This path returns a result to the caller after any required cleanup. Check finally blocks, which may run before the function leaves.",
      "understanding-step-throw":"This path raises an error. Look for a matching handler; normal execution does not continue here.",
      "understanding-step-mutation":"A value changes here. Compare the target and the new expression, then follow where that value is used.",
      "understanding-step-call":"This step delegates work to another function. Open the connected function to inspect its behavior.",
      "understanding-step-effect":"This call may affect something outside this function. The source evidence below shows what is known.",
      "understanding-step-render":"This creates a UI description. Rendering a child and invoking an event handler have different timing.",
      "understanding-step-event":"This connects an event handler. Registration and later callback execution are separate steps.",
      "understanding-step-try":"Normal work, errors and cleanup have separate paths here. Compare catch/except and finally with the main body.",
      "understanding-step-exit":"This marks the end of the displayed function flow. Check return and error paths for how it can finish."
    });
    Object.assign(projectAnalyzerUiCopy.ko, {
      "open-statement":"소스 열기",
      "understanding-title":"한눈에 이해", "understanding-hint":"받는 값을 보고, 흐름이 갈리는 곳을 따라간 뒤, 함수가 남기는 결과를 확인하세요.",
      "understanding-inputs":"1 · 무엇을 받나요?", "understanding-decisions":"2 · 어디서 흐름이 갈리나요?", "understanding-outcomes":"3 · 무엇을 남기나요?",
      "understanding-no-inputs":"선언된 매개변수 없음", "understanding-more":" 외 {count}개", "understanding-input-action":"입력부터 읽기",
      "understanding-decision-count":"판단하거나 반복하는 곳 {count}개", "understanding-no-decisions":"표시된 코드에 분기·반복 없음", "understanding-decision-action":"첫 판단 읽기",
      "understanding-outcome-returns":"반환 {count}곳", "understanding-outcome-errors":"오류 발생 {count}곳", "understanding-outcome-effects":"확인된 외부 효과 {count}곳",
      "understanding-no-outcomes":"표시된 코드에서 명시적 반환·오류·외부 효과를 확인하지 못함", "understanding-outcome-action":"첫 결과 읽기",
      "understanding-empty":"아직 설명할 코드 단계가 없습니다.", "understanding-documentation":"함수에 작성된 설명",
      "understanding-framework":"{framework} 동작 이해하기", "understanding-framework-note":"소스에 연결된 프레임워크 동작 규칙입니다. 실제 호출 시점·요청·SQL을 관찰한 결과는 아닙니다.",
      "understanding-framework-more":"분석 한계로 추가 근거 {count}개를 생략했습니다.", "understanding-framework-limited":"분석 범위 안에서 확인한 내용입니다.",
      "understanding-graph":"그래프에서 찾기", "understanding-source":"근거 소스 열기", "understanding-evidence-missing":"현재 분석에 열 수 있는 소스 근거가 없습니다.",
      "understanding-no-framework":"이 함수에서 소스로 확인된 React·Django 동작은 아직 없습니다.",
      "understanding-role-component":"컴포넌트", "understanding-role-hooks":"React Hook 사용", "understanding-role-view":"요청 처리 함수", "understanding-role-signal":"신호 수신 함수", "understanding-role-middleware":"미들웨어", "understanding-role-usage":"프레임워크 API 사용",
      "understanding-phase-render":"렌더 계산 중", "understanding-phase-commit":"DOM 반영 뒤", "understanding-phase-event":"이벤트 발생 시", "understanding-phase-request":"요청 처리 중", "understanding-phase-query":"DB 작업", "understanding-phase-response":"응답 생성", "understanding-phase-registration":"콜백 등록",
      "understanding-step-heading":"이 단계는 이렇게 읽으세요",
      "understanding-step-entry":"여기서 시작합니다. 함수에 들어오는 값을 확인한 뒤 첫 문장으로 이동하세요.",
      "understanding-step-condition":"흐름이 갈리는 곳입니다. 아래에서 조건이 참일 때와 거짓일 때 이어질 코드를 비교하세요.",
      "understanding-step-loop":"본문을 반복할 수 있는 곳입니다. 어떤 조건에서 계속하고 어디로 빠져나오는지 확인하세요.",
      "understanding-step-switch":"값에 맞는 case로 이동합니다. 일치하는 값이 없을 때의 기본 경로도 확인하세요.",
      "understanding-step-return":"이 경로의 결과를 호출한 쪽에 돌려줍니다. 함수가 끝나기 전에 실행되는 finally 같은 정리 작업도 확인하세요.",
      "understanding-step-throw":"오류를 발생시키는 경로입니다. 이를 처리할 catch·except가 있는지 확인하세요.",
      "understanding-step-mutation":"값이 바뀌는 곳입니다. 바뀌는 대상과 새 식을 비교한 뒤 그 값을 어디에서 사용하는지 따라가세요.",
      "understanding-step-call":"다른 함수에 작업을 넘기는 단계입니다. 연결된 함수를 열면 내부 동작까지 확인할 수 있습니다.",
      "understanding-step-effect":"함수 밖의 상태에 영향을 줄 수 있는 호출입니다. 아래 소스 근거에서 확인된 범위를 살펴보세요.",
      "understanding-step-render":"화면에 표시할 내용을 구성합니다. 자식 컴포넌트를 렌더하는 시점과 이벤트 핸들러가 호출되는 시점은 다릅니다.",
      "understanding-step-event":"이벤트 핸들러를 연결합니다. 지금 등록하는 동작과 나중에 콜백을 실행하는 동작을 나누어 읽으세요.",
      "understanding-step-try":"정상 처리, 오류 처리, 정리 작업의 경로를 나누는 곳입니다. 본문과 catch·except, finally를 비교하세요.",
      "understanding-step-exit":"표시된 함수 흐름의 끝입니다. 어떤 반환·오류 경로로 여기까지 올 수 있는지 확인하세요."
    });
  `;
}
