/** Bilingual input-quality explanations and explicit model-request lifecycle states. */
const en = {
  "scenario-ai-action": "Find inputs with neural network",
  "scenario-ai-help": "Learns from numbers, text, collection sizes and calculated condition values on your CPU. Compare inputs that change a branch result, then apply a case.",
  "scenario-ai-idle": "Uses declared input shapes and caller tuples. Source code stays on this computer.",
  "scenario-ai-pending": "Training locally, estimating boundary inputs, and checking their paths…",
  "scenario-ai-cancel": "Cancel suggestions",
  "scenario-ai-ready": "Added {count} suggestions · {model}",
  "scenario-ai-rejected": "Excluded {count} invalid, duplicate or redundant proposals.",
  "scenario-ai-empty": "No additional checked boundary pair was found within the search limits. This does not prove the remaining branches unreachable.",
  "scenario-ai-unavailable": "Not enough supported condition values or complete inputs to train. Supports bounded TypeScript/JavaScript calculations; unsupported calls and framework state remain unknown.",
  "scenario-ai-denied": "Local inference could not start. Reopen the function and retry.",
  "scenario-ai-timeout": "Local inference exceeded its time limit. Try a smaller function.",
  "scenario-ai-invalid-response": "Generated inputs failed validation. Reopen the function and retry.",
  "scenario-ai-failed": "Local training could not finish. Reopen the function and retry.",
  "scenario-ai-cancelled": "Suggestions cancelled.",
  "scenario-ai-stale": "The function context expired. Reopen this function to request suggestions.",
  "scenario-ai-limit": "Up to 8 neural cases are retained for this function.",
  "scenario-neural-training": "Training: {training} samples · Held out: {validation} samples · Normalized error: {error}. Prediction error, not coverage or confidence.",
  "scenario-quality-heading": "Why this input",
  "scenario-quality-caller": "Keeps the arguments from one actual callsite together.",
  "scenario-quality-baseline": "Provides a declared type or default baseline for comparison with boundary cases.",
  "scenario-quality-boundary": "Tests a source boundary while retaining the other input fields: {conditions}",
  "scenario-quality-model": "Input estimated by a locally trained network and checked against the function’s control flow.",
  "scenario-quality-verified": "Supported static path checked · {count} branch outcomes",
  "scenario-quality-partial": "Static prefix checked · {count} branch outcomes",
  "scenario-quality-coverage": "Static branch outcomes checked: {covered}/{total}. Remaining outcomes are unconfirmed, not proven unreachable.",
  "scenario-quality-assumptions": "Model assumptions: {text}",
  "scenario-quality-gap-unknown-input": "A required value is unknown.",
  "scenario-quality-gap-unsupported-expression": "A calculation or shared-object write is outside this checker.",
  "scenario-quality-gap-external-state": "An external call or effect needs runtime context.",
  "scenario-quality-gap-control-gap": "The next control transition is not resolved.",
  "scenario-quality-gap-loop-budget": "The bounded loop check stopped.",
  "scenario-quality-gap-step-budget": "The bounded path check stopped.",
  "scenario-quality-gap-language-gap": "Concrete path checks currently cover TypeScript and JavaScript.",
  "tutor-seed-model": "Neural input · case {ordinal}"
};
const ko: Record<keyof typeof en, string> = {
  "scenario-ai-action": "신경망으로 입력 찾기",
  "scenario-ai-help": "숫자·문자열·배열 길이와 계산된 조건값을 로컬 CPU에서 학습합니다. 분기 결과가 달라지는 입력을 비교한 뒤 적용하세요.",
  "scenario-ai-idle": "선언된 입력 구조와 호출부의 인수 조합을 사용합니다. 소스는 이 컴퓨터에 머뭅니다.",
  "scenario-ai-pending": "로컬 학습 → 경계 입력 추정 → 경로 확인 중…",
  "scenario-ai-cancel": "제안 취소",
  "scenario-ai-ready": "제안 {count}개 추가 · {model}",
  "scenario-ai-rejected": "형식 오류·중복·추가 설명력이 없는 제안 {count}개 제외",
  "scenario-ai-empty": "탐색 범위에서 추가 경계 입력 쌍을 찾지 못했습니다. 남은 분기에 도달할 수 없다는 뜻은 아닙니다.",
  "scenario-ai-unavailable": "학습할 조건값이나 완전한 입력이 부족합니다. 현재 TypeScript·JavaScript의 제한된 계산을 지원하며, 지원하지 않는 호출과 프레임워크 상태는 미확인으로 남깁니다.",
  "scenario-ai-denied": "로컬 추론을 시작하지 못했습니다. 함수를 다시 열어 시도하세요.",
  "scenario-ai-timeout": "로컬 추론 시간 한도를 넘었습니다. 더 작은 함수에서 시도하세요.",
  "scenario-ai-invalid-response": "생성한 입력이 유효성 검사를 통과하지 못했습니다. 함수를 다시 열어 시도하세요.",
  "scenario-ai-failed": "로컬 학습을 마치지 못했습니다. 함수를 다시 열어 시도하세요.",
  "scenario-ai-cancelled": "제안을 취소했습니다.",
  "scenario-ai-stale": "함수 분석 문맥이 만료됐습니다. 함수를 다시 열어 제안받으세요.",
  "scenario-ai-limit": "함수당 신경망 사례를 최대 8개 보관합니다.",
  "scenario-neural-training": "학습 {training}개 · 별도 검증 {validation}개 · 정규화 오차 {error}. 예측 오차이며, 분기 확인율이나 신뢰도가 아닙니다.",
  "scenario-quality-heading": "추천 이유",
  "scenario-quality-caller": "실제 한 호출부에서 함께 전달한 인수 조합을 유지합니다.",
  "scenario-quality-baseline": "선언된 타입이나 기본값을 경계 사례와 비교할 기준으로 삼습니다.",
  "scenario-quality-boundary": "다른 입력 필드를 유지하면서 소스의 경계를 확인합니다: {conditions}",
  "scenario-quality-model": "자체 신경망이 로컬에서 학습해 추정하고 함수의 제어 흐름으로 검사한 입력입니다.",
  "scenario-quality-verified": "지원 범위의 정적 경로 확인 · 분기 결과 {count}개",
  "scenario-quality-partial": "정적 경로 일부 확인 · 분기 결과 {count}개",
  "scenario-quality-coverage": "정적으로 확인한 분기 결과 {covered}/{total}개. 나머지는 미확인이며, 도달 불가능하다는 뜻은 아닙니다.",
  "scenario-quality-assumptions": "모델이 둔 가정: {text}",
  "scenario-quality-gap-unknown-input": "필요한 입력값을 알 수 없어 멈췄습니다.",
  "scenario-quality-gap-unsupported-expression": "계산식이나 공유 객체 변경이 이 검사기의 지원 범위를 벗어납니다.",
  "scenario-quality-gap-external-state": "외부 호출이나 부수 효과에 실행 문맥이 필요합니다.",
  "scenario-quality-gap-control-gap": "다음 제어 흐름을 확정할 수 없습니다.",
  "scenario-quality-gap-loop-budget": "반복 분석 한도에 도달했습니다.",
  "scenario-quality-gap-step-budget": "경로 분석 한도에 도달했습니다.",
  "scenario-quality-gap-language-gap": "구체적인 경로 검사는 현재 TypeScript와 JavaScript를 지원합니다.",
  "tutor-seed-model": "신경망 입력 · 사례 {ordinal}"
};

/** Extends the shared browser catalog without reinitializing presentation state. */
export function getScenarioInputCatalogSource(): string {
  return `Object.assign(projectAnalyzerUiCopy.en, ${JSON.stringify(en)}); Object.assign(projectAnalyzerUiCopy.ko, ${JSON.stringify(ko)});`;
}
