/** Bilingual input-quality explanations and explicit model-request lifecycle states. */
const en = {
  "scenario-ai-action": "Suggest AI edge cases",
  "scenario-ai-help": "Sends the selected function and up to 4 caller snippets to a model you choose in VS Code. Review each proposal before applying its inputs.",
  "scenario-ai-idle": "AI can suggest domain cases from the interface and caller context.",
  "scenario-ai-pending": "Choose a model in VS Code. Generating and checking input suggestions…",
  "scenario-ai-cancel": "Cancel suggestions",
  "scenario-ai-ready": "Added {count} suggestions · {model}",
  "scenario-ai-rejected": "Excluded {count} invalid, duplicate or redundant proposals.",
  "scenario-ai-empty": "No additional useful inputs passed the checks. You can request another set.",
  "scenario-ai-unavailable": "No usable model or bounded input context is available. Connect a chat model in VS Code and retry.",
  "scenario-ai-denied": "Model access was not granted. Allow this extension to use the model in VS Code, then retry.",
  "scenario-ai-timeout": "The model took too long. Retry or choose another model.",
  "scenario-ai-invalid-response": "The model did not return valid input data. Retry or choose another model.",
  "scenario-ai-failed": "Could not get suggestions. Check model availability or quota in VS Code and retry.",
  "scenario-ai-cancelled": "Suggestions cancelled.",
  "scenario-ai-stale": "The function context expired. Reopen this function to request suggestions.",
  "scenario-ai-limit": "Up to 8 AI cases are retained for this function.",
  "scenario-quality-heading": "Why this input",
  "scenario-quality-caller": "Keeps the arguments from one actual callsite together.",
  "scenario-quality-baseline": "Provides a declared type or default baseline for comparison with boundary cases.",
  "scenario-quality-boundary": "Tests a source boundary while retaining the other input fields: {conditions}",
  "scenario-quality-model": "AI proposal inferred from the function interface and caller context.",
  "scenario-quality-verified": "Supported static path checked · {count} branch outcomes",
  "scenario-quality-partial": "Static prefix checked · {count} branch outcomes",
  "scenario-quality-coverage": "Static branch outcomes checked: {covered}/{total}. Remaining outcomes are unconfirmed, not proven unreachable.",
  "scenario-quality-assumptions": "Model assumptions: {text}",
  "scenario-quality-gap-unknown-input": "A required value is unknown.",
  "scenario-quality-gap-unsupported-expression": "A calculation or shared-object write is outside this checker.",
  "scenario-quality-gap-external-state": "An external call or effect needs runtime context.",
  "scenario-quality-gap-control-gap": "The next control transition is not resolved.",
  "scenario-quality-gap-loop-budget": "The bounded loop check stopped.",
  "scenario-quality-gap-step-budget": "The bounded path check stopped.",
  "scenario-quality-gap-language-gap": "Concrete path checks currently cover TypeScript and JavaScript.",
  "tutor-seed-model": "AI proposal · case {ordinal}"
};
const ko: Record<keyof typeof en, string> = {
  "scenario-ai-action": "AI 에지케이스 제안",
  "scenario-ai-help": "선택한 함수와 최대 4개 호출부 코드를 VS Code에서 선택할 모델에 전달합니다. 제안을 검토한 뒤 입력을 적용하세요.",
  "scenario-ai-idle": "함수 인터페이스와 호출 문맥으로 도메인 에지케이스를 제안합니다.",
  "scenario-ai-pending": "VS Code에서 모델을 선택하세요. 입력을 제안하고 경로를 확인하는 중…",
  "scenario-ai-cancel": "제안 취소",
  "scenario-ai-ready": "제안 {count}개 추가 · {model}",
  "scenario-ai-rejected": "형식 오류·중복·추가 설명력이 없는 제안 {count}개 제외",
  "scenario-ai-empty": "검사를 통과한 추가 입력이 없습니다. 다시 제안받을 수 있습니다.",
  "scenario-ai-unavailable": "사용할 모델이나 분석 문맥이 없습니다. VS Code에 채팅 모델을 연결한 뒤 다시 시도하세요.",
  "scenario-ai-denied": "모델 사용이 허용되지 않았습니다. VS Code에서 이 확장에 모델 사용을 허용한 뒤 다시 시도하세요.",
  "scenario-ai-timeout": "모델 응답 시간이 초과됐습니다. 다시 시도하거나 다른 모델을 선택하세요.",
  "scenario-ai-invalid-response": "모델 응답을 입력값으로 해석할 수 없습니다. 다시 시도하거나 다른 모델을 선택하세요.",
  "scenario-ai-failed": "제안을 받지 못했습니다. VS Code에서 모델 연결과 사용 한도를 확인한 뒤 다시 시도하세요.",
  "scenario-ai-cancelled": "제안을 취소했습니다.",
  "scenario-ai-stale": "함수 분석 문맥이 만료됐습니다. 함수를 다시 열어 제안받으세요.",
  "scenario-ai-limit": "함수당 AI 사례를 최대 8개 보관합니다.",
  "scenario-quality-heading": "추천 이유",
  "scenario-quality-caller": "실제 한 호출부에서 함께 전달한 인수 조합을 유지합니다.",
  "scenario-quality-baseline": "선언된 타입이나 기본값을 경계 사례와 비교할 기준으로 삼습니다.",
  "scenario-quality-boundary": "다른 입력 필드를 유지하면서 소스의 경계를 확인합니다: {conditions}",
  "scenario-quality-model": "함수 인터페이스와 호출 문맥을 바탕으로 AI가 추론한 제안입니다.",
  "scenario-quality-verified": "지원 범위의 정적 경로 확인 · 분기 결과 {count}개",
  "scenario-quality-partial": "정적 경로 일부 확인 · 분기 결과 {count}개",
  "scenario-quality-coverage": "정적으로 확인한 분기 결과 {covered}/{total}개. 나머지는 미확인이며, 도달 불가능하다는 뜻은 아닙니다.",
  "scenario-quality-assumptions": "모델이 둔 가정: {text}",
  "scenario-quality-gap-unknown-input": "필요한 입력값을 알 수 없어 멈췄습니다.",
  "scenario-quality-gap-unsupported-expression": "계산식이나 공유 객체 변경이 이 검사기의 지원 범위를 벗어납니다.",
  "scenario-quality-gap-external-state": "외부 호출이나 부수 효과에 실행 문맥이 필요합니다.",
  "scenario-quality-gap-control-gap": "다음 제어 흐름을 확정할 수 없습니다.",
  "scenario-quality-gap-loop-budget": "반복 분석 한도에 도달했습니다.",
  "scenario-quality-gap-step-budget": "경로 분석 한도에 도달했습니다.",
  "scenario-quality-gap-language-gap": "구체적인 경로 검사는 현재 TypeScript와 JavaScript를 지원합니다.",
  "tutor-seed-model": "AI 제안 · 사례 {ordinal}"
};

/** Extends the shared browser catalog without reinitializing presentation state. */
export function getScenarioInputCatalogSource(): string {
  return `Object.assign(projectAnalyzerUiCopy.en, ${JSON.stringify(en)}); Object.assign(projectAnalyzerUiCopy.ko, ${JSON.stringify(ko)});`;
}
